apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: $(dockerRegistryServiceConnection).azurecr.io./$(Build.Repository.Name)/$(Build.SourceBranch)/$(tag)
        name: hello-world
        ports:
        - containerPort: 8080